import GithubLogo from '@/app/(website)/_components/logos/githubLogo'
import InstagramLogo from '@/app/(website)/_components/logos/instagramLogo'
import YoutubeLogo from '@/app/(website)/_components/logos/youtubeLogo'
import { Button } from '@repo/core-ui/components/ui/button'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@repo/core-ui/components/ui/collapsible'
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
} from '@repo/core-ui/components/ui/navigation-menu'
import { Separator } from '@repo/core-ui/components/ui/separator'
import {
  Sheet,
  SheetContent,
  SheetTrigger,
} from '@repo/core-ui/components/ui/sheet'
import '@repo/core-ui/globals.css'
import { cn } from '@repo/core-ui/lib/utils'
import {
  ChevronRightIcon,
  CircleDollarSignIcon,
  InfoIcon,
  LayoutListIcon,
  MenuIcon,
  MessageCircleXIcon,
  NotepadTextIcon,
  RocketIcon,
} from 'lucide-react'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import FacebookLogo from './_components/logos/facebookLogo'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className="dark antialiased" lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <div className="flex min-h-screen w-full flex-col">
          <header className="bg-background/1 fixed top-0 z-40 flex h-16 w-full items-center px-4 backdrop-blur-sm md:px-6">
            <div className="container flex w-full items-center justify-between gap-4">
              <Link
                className="flex items-center gap-2 text-lg font-semibold md:text-base"
                href="#"
              >
                <RocketIcon className="h-6 w-6" />
                <h1 className="px-1 text-2xl">SaaS Line</h1>
              </Link>

              <div className="hidden md:flex md:gap-4">
                <NavigationMenu>
                  <NavigationMenuList className="m-0 gap-4 p-0">
                    <NavigationMenuItem className="m-0 p-0">
                      <NavigationMenuLink
                        asChild
                        className="m-0 h-auto p-0 text-foreground hover:bg-inherit hover:text-muted-foreground focus:bg-inherit focus:text-muted-foreground data-[state=open]:bg-inherit"
                      >
                        <Link
                          className="select-none text-sm leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                          href="#"
                        >
                          Home
                        </Link>
                      </NavigationMenuLink>
                    </NavigationMenuItem>
                    <NavigationMenuItem className="m-0 p-0">
                      <NavigationMenuLink
                        asChild
                        className="m-0 h-auto p-0 text-foreground hover:bg-inherit hover:text-muted-foreground focus:bg-inherit focus:text-muted-foreground data-[state=open]:bg-inherit"
                      >
                        <Link
                          className="select-none text-sm leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                          href="#"
                        >
                          Pricing
                        </Link>
                      </NavigationMenuLink>
                    </NavigationMenuItem>
                    <NavigationMenuItem className="m-0 p-0">
                      <NavigationMenuLink
                        asChild
                        className="m-0 h-auto p-0 text-foreground hover:bg-inherit hover:text-muted-foreground focus:bg-inherit focus:text-muted-foreground data-[state=open]:bg-inherit"
                      >
                        <Link
                          className="select-none text-sm leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                          href="#"
                        >
                          Blog
                        </Link>
                      </NavigationMenuLink>
                    </NavigationMenuItem>
                    <NavigationMenuItem className="m-0 p-0">
                      <NavigationMenuLink
                        asChild
                        className="m-0 h-auto p-0 text-foreground hover:bg-inherit hover:text-muted-foreground focus:bg-inherit focus:text-muted-foreground data-[state=open]:bg-inherit"
                      >
                        <Link
                          className="select-none text-sm leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                          href="#"
                        >
                          About
                        </Link>
                      </NavigationMenuLink>
                    </NavigationMenuItem>
                    <NavigationMenuItem className="m-0 p-0">
                      <NavigationMenuTrigger className="m-0 h-auto bg-inherit p-0 text-sm text-foreground hover:bg-inherit hover:text-muted-foreground data-[state=open]:bg-inherit">
                        Pages
                      </NavigationMenuTrigger>
                      <NavigationMenuContent>
                        <ul className="m-0 ml-0 grid w-[340px] list-none gap-1 py-4">
                          <li className="m-0">
                            <NavigationMenuLink asChild>
                              <Link
                                className="flex select-none gap-4 space-y-1 rounded-md p-3 pl-6 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                                href="#"
                              >
                                <CircleDollarSignIcon className="self-center" />
                                <div>
                                  <p className="text-sm font-medium leading-none">
                                    Pricing
                                  </p>
                                  <p className="mt-1 text-sm text-muted-foreground">
                                    Payment packages and FAQ
                                  </p>
                                </div>
                              </Link>
                            </NavigationMenuLink>
                          </li>
                          <li className="m-0">
                            <NavigationMenuLink asChild>
                              <Link
                                className="flex select-none gap-4 space-y-1 rounded-md p-3 pl-6 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                                href="#"
                              >
                                <InfoIcon className="self-center" />
                                <div>
                                  <p className="text-sm font-medium leading-none">
                                    About
                                  </p>
                                  <p className="mt-1 text-sm text-muted-foreground">
                                    Company and team details
                                  </p>
                                </div>
                              </Link>
                            </NavigationMenuLink>
                          </li>
                          <li className="m-0">
                            <NavigationMenuLink asChild>
                              <Link
                                className="flex select-none gap-4 space-y-1 rounded-md p-3 pl-6 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                                href="#"
                              >
                                <LayoutListIcon className="self-center" />
                                <div>
                                  <p className="text-sm font-medium leading-none">
                                    Blog List
                                  </p>
                                  <p className="mt-1 text-sm text-muted-foreground">
                                    Your blog&apos;s landing page
                                  </p>
                                </div>
                              </Link>
                            </NavigationMenuLink>
                          </li>
                          <li className="m-0">
                            <NavigationMenuLink asChild>
                              <Link
                                className="flex select-none gap-4 space-y-1 rounded-md p-3 pl-6 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                                href="#"
                              >
                                <NotepadTextIcon className="self-center" />
                                <div>
                                  <p className="text-sm font-medium leading-none">
                                    Blog Post
                                  </p>
                                  <p className="mt-1 text-sm text-muted-foreground">
                                    Latest blog post
                                  </p>
                                </div>
                              </Link>
                            </NavigationMenuLink>
                          </li>
                          <li className="m-0">
                            <NavigationMenuLink asChild>
                              <Link
                                className="flex select-none gap-4 space-y-1 rounded-md p-3 pl-6 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground"
                                href="#"
                              >
                                <MessageCircleXIcon className="self-center" />
                                <div>
                                  <p className="text-sm font-medium leading-none">
                                    404 Error
                                  </p>
                                  <p className="mt-1 text-sm text-muted-foreground">
                                    Page not found error
                                  </p>
                                </div>
                              </Link>
                            </NavigationMenuLink>
                          </li>
                        </ul>
                      </NavigationMenuContent>
                    </NavigationMenuItem>
                  </NavigationMenuList>
                </NavigationMenu>

                <div className="flex gap-2">
                  <Button asChild variant="outline">
                    <Link href="/app">Login</Link>
                  </Button>
                  <Button>Sign Up</Button>
                </div>
              </div>

              <Sheet>
                <SheetTrigger asChild>
                  <Button
                    className="shrink-0 md:hidden"
                    size="icon"
                    variant="outline"
                  >
                    <MenuIcon className="h-5 w-5" />
                    <span className="sr-only">Toggle navigation menu</span>
                  </Button>
                </SheetTrigger>
                <SheetContent
                  className="flex flex-col justify-between px-0"
                  side="left"
                >
                  <nav className="grid gap-6 text-lg font-medium">
                    <Link
                      className="mb-6 flex items-center gap-2 pl-6 text-lg font-semibold"
                      href="#"
                    >
                      <RocketIcon className="h-6 w-6" />
                      <h1 className="px-1 text-2xl">SaaS Line</h1>
                    </Link>
                    <Link className="pl-6 text-foreground" href="#">
                      Home
                    </Link>
                    <Link
                      className="pl-6 text-muted-foreground hover:text-foreground"
                      href="#"
                    >
                      Pricing
                    </Link>
                    <Link
                      className="pl-6 text-muted-foreground hover:text-foreground"
                      href="#"
                    >
                      Blog
                    </Link>
                    <Link
                      className="pl-6 text-muted-foreground hover:text-foreground"
                      href="#"
                    >
                      About
                    </Link>
                    <Collapsible className="grid gap-1">
                      <CollapsibleTrigger className="-mt-1 flex items-center justify-between rounded-md px-4 py-2 pl-6 text-muted-foreground transition-colors hover:bg-gray-200 hover:text-foreground dark:hover:bg-gray-800">
                        Pages
                        <ChevronRightIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-90" />
                      </CollapsibleTrigger>
                      <CollapsibleContent className="space-y-1 pl-4">
                        <ul className="my-0 flex list-none flex-col gap-6 pt-4 text-base font-medium [&>li]:mt-0">
                          <li>
                            <Link
                              className="text-muted-foreground hover:text-foreground"
                              href="#"
                            >
                              Pricing
                            </Link>
                          </li>
                          <li>
                            <Link
                              className="text-muted-foreground hover:text-foreground"
                              href="#"
                            >
                              About
                            </Link>
                          </li>
                          <li>
                            <Link
                              className="text-muted-foreground hover:text-foreground"
                              href="#"
                            >
                              Blog List
                            </Link>
                          </li>
                          <li>
                            <Link
                              className="text-muted-foreground hover:text-foreground"
                              href="#"
                            >
                              Blog Post
                            </Link>
                          </li>
                          <li>
                            <Link
                              className="text-muted-foreground hover:text-foreground"
                              href="#"
                            >
                              404 Error
                            </Link>
                          </li>
                        </ul>
                      </CollapsibleContent>
                    </Collapsible>
                  </nav>

                  <div className="flex flex-col gap-6 p-6">
                    <Button asChild size="lg" variant="outline">
                      <Link href="/app">Login</Link>
                    </Button>
                    <Button size="lg">Sign Up</Button>
                  </div>
                </SheetContent>
              </Sheet>
            </div>
          </header>

          {children}

          <footer className="bg-blue-700">
            <div className="container grid gap-10 py-24 pb-8 md:grid-cols-[2fr_1fr_1fr] lg:grid-cols-[2fr_1fr_1fr_1fr_2fr]">
              <div className="flex flex-col gap-8">
                <Link
                  className="flex items-center gap-2 text-lg font-semibold md:text-base"
                  href="#"
                >
                  <RocketIcon className="h-6 w-6 text-white" />
                  <h1 className="px-1 text-2xl text-white">SaaS Line</h1>
                </Link>
                <p className="text-slate-300">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
                  semper ligula eu elementum molestie.
                </p>
                <div className="flex gap-8">
                  <Link href="#" title="Facebook">
                    <FacebookLogo
                      className="fill-slate-300 hover:fill-slate-50"
                      width={28}
                    />
                  </Link>
                  <Link href="#" title="Instagram">
                    <InstagramLogo
                      className="fill-slate-300 hover:fill-slate-50"
                      width={28}
                    />
                  </Link>
                  <Link href="#" title="Youtube">
                    <YoutubeLogo
                      className="fill-slate-300 hover:fill-slate-50"
                      width={28}
                    />
                  </Link>
                  <Link href="#" title="Github">
                    <GithubLogo
                      className="fill-slate-300 hover:fill-slate-50"
                      width={28}
                    />
                  </Link>
                </div>
              </div>

              <div className="flex flex-col gap-6">
                <h4 className="text-white">Products</h4>

                <ul className="m-0 flex list-none flex-col gap-2">
                  <li>
                    <Link className="text-slate-300" href="#">
                      Chat App
                    </Link>
                  </li>
                  <li>
                    <Link className="text-slate-300" href="#">
                      Browser Extension
                    </Link>
                  </li>
                  <li>
                    <Link className="text-slate-300" href="#">
                      Photo Editor
                    </Link>
                  </li>
                  <li>
                    <Link className="text-slate-300" href="#">
                      Video Editor
                    </Link>
                  </li>
                </ul>
              </div>

              <div className="flex flex-col gap-6">
                <h4 className="text-white">Features</h4>

                <ul className="m-0 flex list-none flex-col gap-2">
                  <li>
                    <Link className="text-slate-300" href="#">
                      Authentication
                    </Link>
                  </li>
                  <li>
                    <Link className="text-slate-300" href="#">
                      Firewall
                    </Link>
                  </li>
                  <li>
                    <Link className="text-slate-300" href="#">
                      Optimized Storage
                    </Link>
                  </li>
                  <li>
                    <Link className="text-slate-300" href="#">
                      Cloud Backup
                    </Link>
                  </li>
                </ul>
              </div>

              <div className="flex flex-col gap-6">
                <h4 className="text-white">Company</h4>

                <ul className="m-0 flex list-none flex-col gap-2">
                  <li>
                    <Link className="text-slate-300" href="#">
                      About Us
                    </Link>
                  </li>
                  <li>
                    <Link className="text-slate-300" href="#">
                      Contact Us
                    </Link>
                  </li>
                  <li>
                    <Link className="text-slate-300" href="#">
                      Careers
                    </Link>
                  </li>
                  <li>
                    <Link className="text-slate-300" href="#">
                      Press
                    </Link>
                  </li>
                </ul>
              </div>

              <div className="flex flex-col gap-6 md:col-span-2 lg:col-span-1">
                <h4 className="text-white">Latest Blog</h4>

                <ul className="m-0 flex list-none flex-col gap-4">
                  <li>
                    <Link
                      className="flex items-start gap-6 text-slate-300"
                      href="#"
                    >
                      <Image
                        alt="How to significantly reduce your AWS bill?"
                        className="rounded-sm"
                        height={80}
                        src="/img/mac-desktop.jpg"
                        width={80}
                      />
                      <p className="text-slate-300">
                        How to significantly reduce your AWS bill?
                      </p>
                    </Link>
                  </li>
                  <li>
                    <Link
                      className="flex items-start gap-6 text-slate-300"
                      href="#"
                    >
                      <Image
                        alt="Avoiding unnecessary rendering with React/Nextjs"
                        className="rounded-sm"
                        height={80}
                        src="/img/pair-programming.jpg"
                        width={80}
                      />
                      <p className="text-slate-300">
                        Avoiding unnecessary rendering with React/Nextjs
                      </p>
                    </Link>
                  </li>
                </ul>
              </div>
            </div>

            <Separator className="my-4 bg-slate-400/50" />

            <div className="container flex justify-between py-6">
              <div className="flex gap-6">
                <Link className="text-slate-300" href="#">
                  Privacy Policy
                </Link>
                <Link className="text-slate-300" href="#">
                  Refund Policy
                </Link>
                <Link className="text-slate-300" href="#">
                  Terms of Service
                </Link>
              </div>
              <div>
                <p className="text-slate-300">
                  &copy; 2022 SaaS Line. All rights reserved.
                </p>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  )
}
